# This is a basic workflow that is manually triggered
name: ChatApp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # List contents of the root directory
      - name: List contents of root directory
        run: ls -R

      # Compile Java classes
      - name: Compile classes
        working-directory: ./ChatApp/ChatApp/src/main/java
        run: |
          javac com/rochelle/chatapp/Login.java com/rochelle/chatapp/ChatApp.java
          ls -R com/rochelle/chatapp

      # List contents of the target directory after compile
      - name: List contents of target directory after compile
        working-directory: ./ChatApp/ChatApp/target
        run: ls -R

      # Run JUnit tests and output report
      - name: Run JUnit tests and output report
        working-directory: ./ChatApp/ChatApp
        run: |
          java -jar ../junit-platform-console-standalone-1.6.0.jar \
            --class-path "./target/classes:./target/test-classes" \
            --reports-dir ./target/surefire-reports \
            --details=tree \
            --scan-class-path

      # Upload the JUnit test results
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Test Results
          path: ./ChatApp/ChatApp/target/surefire-reports

      # Archive build results
      - name: Archive Build
        uses: actions/upload-artifact@v4
        with:
          name: ChatApp Build
          path: ./ChatApp/ChatApp/target/classes

