name: ChatApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3.1.1
      
      # List contents of the root directory
      - name: List contents of root directory
        run: ls -a
        
      # Compile the classes
      - name: Compile classes
        working-directory: ./ChatApp/src
        run: |
          javac -cp "../lib/junit-platform-console-standalone-1.9.3.jar" ChatApp/ChatApp.java ChatApp/Login.java
        
      # List contents after compile
      - name: List contents of src directory after compile
        working-directory: ./ChatApp/src/ChatApp
        run: ls
      
      # Create tests directory if it doesn't exist
      - name: Create tests directory
        run: mkdir -p ./ChatApp/tests

      # Copy compiled classes to tests directory
      - name: Copy compiled classes to testresources directory
        working-directory: ./ChatApp/src/ChatApp
        run: cp -t ../../tests ChatApp.class Login.class

      # Copy compiled test classes to tests directory
      - name: Copy compiled test classes to testresources directory
        working-directory: ./ChatApp/test/ChatApp
        run: cp -t ../../../tests ChatAppTest.class

      # List contents of test package
      - name: List contents of test package
        working-directory: ./ChatApp/tests
        run: ls

      # Run tests using JUnit Console
      - name: Run Login Class tests and output report
        working-directory: ./ChatApp
        run: |
          java -jar "./lib/junit-platform-console-standalone-1.9.3.jar" \
          --class-path "./tests:./lib/junit-platform-console-standalone-1.9.3.jar" \
          --reports-dir ${{github.workspace}}/junit-reports \
          --details=tree \
          --scan-class-path

      # Upload the JUnit test results
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v3.1.1
        with:
          name: JUnit Test Results
          path: ${{github.workspace}}/junit-reports
