name: ChatApp CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn -B -f ChatApp/pom.xml clean verify

      - name: List target directory
        run: ls -R ChatApp/target

      - name: Upload JUnit test results
        if: always()  # Ensures upload even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Test Results
          path: ChatApp/target/surefire-reports
