# This is a basic workflow that is manually triggered
name: ChatApp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven dependencies to speed up build
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build the project with Maven
      - name: Build with Maven
        run: mvn -f ./ChatApp/pom.xml clean package

      # List contents of the target directory after build
      - name: List target directory
        run: ls -R ./ChatApp/target

      # Run the tests
      - name: Run tests with Maven
        run: mvn -f ./ChatApp/pom.xml test

      # Upload the JUnit test results
      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Test Results
          path: ./ChatApp/target/surefire-reports
